typedef struct phonebook {
	char fname[35];
	char mname[35];
	char lname[30];
	double mobile_no;
	char address[50];
	char sex[8];
	char mail[100];
	char dob[20];
}phonebook;
void menu(phonebook *p);
void menuchoice(phonebook *p);
int addrecord(phonebook *p);
int listrecord(phonebook *p, int flag);
int modifyrecord(phonebook *p);
int deleterecord(phonebook *p);
int searchrecord(phonebook *p);
int save(char *data);
int backup(char *fname, char*lname, phonebook *p);
void confirm(phonebook *p, int fun);
void confirmlistcont(phonebook *p);
void search(phonebook *p, char *str, char *column);
void searchon(phonebook *p);
void searchmenu(phonebook *p);
void exitapp();
void login();
void loading(int sec);
void confirmaddrecord(phonebook *p);
int isavailable(phonebook *p);

